using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …
Find the sum of all the even-valued terms in the sequence which do not exceed four million.*/

namespace Euler_Project_CS
{
    class Problem2
    {
        static void Main()
        {

            long trailingN = 1;
            long lastN = 1;
            long currentN = 0;
            long summed = 0;

            while(currentN < 4000000)
            {
                if((currentN % 2) == 0) //checks if value is even. remove for normal fibonacci
                {
                    summed += currentN;
                }

                currentN = trailingN + lastN;
                lastN = trailingN;
                trailingN = currentN;
            }

            Console.WriteLine(summed);

            
            Console.WriteLine("Press any key to exit.");
            Console.ReadKey();
        }
    }
}